# Generated by Django 4.0.4 on 2022-06-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massive_creation', '0002_document1_document2_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='massive_creation/')),
            ],
        ),
        migrations.DeleteModel(
            name='Document1',
        ),
        migrations.DeleteModel(
            name='Document2',
        ),
    ]
