# Generated by Django 4.0.4 on 2022-06-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumer_care', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mc',
            new_name='Cc',
        ),
    ]
